
skillMetadata:
  sections:
    - name: Wiser Hub Details
      fields:
        - type: label
          label: "Provide your Wiser Hub IP address and key"
        - name: wiserhubip
          type: text
          label: IP Address
          value: ""
        - name: wiserkey
          type: password
          label: Wiser key
          value: ""
