
skillMetadata:
  sections:
    - name: Wiser Hub Details
      fields:
        - type: label
          label: "Provide your Wiser Hub IP address and key"
        - name: wiserhubip
          type: text
          label: Wiser Hub IP Address
          value: ""
        - name: wiserkey
          type: password
          label: Wiser Hub key
          value: ""
        - type: label
          label: "Provide your Virtual room name that applies commands to all rooms"
        - name: wiserhousename
          type: text
          label: "house name"
          value: "house"
